version: '3'
services:
  web:
    build: .
    ports:
      - "8980:8980"
#    environment:
#      NODE_ENV: production
#      PORT: 8980
#      DATA_DIR: /data/
#      GITHUB_TOKEN: # GitHub 仓库的令牌
#      GITHUB_REPO: # GitHub 仓库（格式：username/repo）
#      GITHUB_BRANCH: main # 默认分支（可选，默认是 main）
#      TELEGRAM_BOT_TOKEN: # 可选，用于发送 Telegram 消息的机器人令牌
#      TELEGRAM_CHAT_ID: # 可选，指定接收 Telegram 消息的聊天 ID。可以是个人聊天 ID 或群组 ID
#      NAVIGATION_URL: # 可选，指定导航站的 URL，用于在 Telegram 消息中提供链接
#      WEBHOOK_URL: # 可选，Webhook 通知，可联动自动化集成推送到其它平台
#      STORAGE_FILE_PATH: # 可选，持久化存储更新数据，用于嵌入网站等，示例：/data.json，必须是完整文件路径哦！
    env_file:
      - .env
    volumes:
      - ./data:/data # 将本地的 data 目录挂载到容器的 /data 目录
    networks:
      - backend

networks:
  backend:
    driver: bridge
